# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('longtitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
    ]
