# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 13:19
from __future__ import unicode_literals

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20181011_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
    ]
